### ISSUE TITLE
Error in Training PBNS 

### ISSUE THREAD

**Issue by HynDufO** [HugoBA92/PBNS#20]
I tried to run the training code for PBNS both locally and on Google Colab but failed with some weird errors. 

Could you give details about the Python version, required packages and their versions? Btw, how do I train only using CPU?

On Google Colab, it used Python 3.10 with tensorflow 2.15 and tensorflow_graphics 2021.12.3. Here are some errors when run on Colab:
```
...
Traceback (most recent call last):
  File "/content/PBNS/PBNS/train.py", line 80, in <module>
    L_collision, E_collision = collision_loss(pred, model._F, body, model._body_faces, model._config['layers'], thr=collision_dist)
  File "/content/PBNS/PBNS/Losses.py", line 36, in collision_loss
    V_vn = tfg.geometry.representation.mesh.normals.vertex_normals(V, tf.tile(F[None], [V.shape[0], 1, 1]))
AttributeError: module 'tensorflow_graphics' has no attribute 'geometry'
```
Then I tried to fix it by adding `import tensorflow_graphics.geometry.representation as tfggr` (inspired by [this](https://github.com/tensorflow/graphics/issues/580)). 
But then I got this error:
```
2024-01-31 03:36:01.867689: E external/local_xla/xla/stream_executor/cuda/cuda_dnn.cc:9261] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
2024-01-31 03:36:01.867770: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:607] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
2024-01-31 03:36:01.869879: E external/local_xla/xla/stream_executor/cuda/cuda_blas.cc:1515] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
2024-01-31 03:36:01.881347: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
2024-01-31 03:36:03.427875: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT
Building model...
Total cloth area:  1.00306

	---------------------------
	MODEL SUMMARY
	---------------------------
	psd:0	(32, 12037, 3)
	fc0_w:0	(72, 32)
	fc0_b:0	(32,)
	fc1_w:0	(32, 32)
	fc1_b:0	(32,)
	fc2_w:0	(32, 32)
	fc2_b:0	(32,)
	fc3_w:0	(32, 32)
	fc3_b:0	(32,)
	---------------------------
	Total params: 1161056
	---------------------------

Reading data...

Epoch 1
--------------------------
Training...
2024-01-31 03:36:12.630925: W tensorflow/core/framework/op_kernel.cc:1827] INVALID_ARGUMENT: TypeError: Unexpected keyword argument {'n_jobs': -1}
Traceback (most recent call last):

  File "/usr/local/lib/python3.10/dist-packages/tensorflow/python/ops/script_ops.py", line 268, in __call__
    return func(device, token, args)

  File "/usr/local/lib/python3.10/dist-packages/tensorflow/python/ops/script_ops.py", line 146, in __call__
    outputs = self._call(device, args)

  File "/usr/local/lib/python3.10/dist-packages/tensorflow/python/ops/script_ops.py", line 153, in _call
    ret = self._func(*args)

  File "/usr/local/lib/python3.10/dist-packages/tensorflow/python/autograph/impl/api.py", line 643, in wrapper
    return func(*args, **kwargs)

  File "/content/PBNS/PBNS/Losses.py", line 71, in _nearest_neighbour
    return tree.query(V.numpy(), n_jobs=-1)[1]

  File "_ckdtree.pyx", line 786, in scipy.spatial._ckdtree.cKDTree.query

  File "_ckdtree.pyx", line 388, in scipy.spatial._ckdtree.get_num_workers

TypeError: Unexpected keyword argument {'n_jobs': -1}
...
```

**Comment by HynDufO** [comment]
UPD: I solved it. It is the error of scipy version or something. Just change `n_jobs` to `workers` and it will be fine. Btw, thanks for the amazing work.
